import {
  AlertTriangle,
  BarChart,
  Bot,
  CheckSquare,
  Code,
  FileCode,
  FileText,
  Heading1,
  Heading2,
  Heading3,
  Image,
  Info,
  List,
  ListOrdered,
  ListTree,
  MessageCircle,
  Minus,
  Quote,
  StickyNote,
  Table,
  User,
} from 'lucide-react';
import { CommandItem } from './slash-command/SlashCommandMenu';

export const EDITOR_COMMANDS: CommandItem[] = [
  {
    id: 'h1',
    label: 'Heading 1',
    description: '建立大型章節標題',
    icon: Heading1,
    insertText: '# ',
    group: 'Basic',
  },
  {
    id: 'h2',
    label: 'Heading 2',
    description: '建立段落層級標題',
    icon: Heading2,
    insertText: '## ',
    group: 'Basic',
  },
  {
    id: 'h3',
    label: 'Heading 3',
    description: '建立小節標題',
    icon: Heading3,
    insertText: '### ',
    group: 'Basic',
  },
  {
    id: 'bullet-list',
    label: 'Bullet list',
    description: '插入項目清單',
    icon: List,
    insertText: '- ',
    group: 'List',
  },
  {
    id: 'numbered-list',
    label: 'Numbered list',
    description: '插入編號清單',
    icon: ListOrdered,
    insertText: '1. ',
    group: 'List',
  },
  {
    id: 'todo-list',
    label: 'Task list',
    description: '插入待辦清單',
    icon: CheckSquare,
    insertText: '- [ ] ',
    group: 'List',
  },
  {
    id: 'quote',
    label: 'Quote',
    description: '插入引用段落',
    icon: Quote,
    insertText: '> ',
    group: 'Basic',
  },
  {
    id: 'divider',
    label: 'Divider',
    description: '插入水平分隔線',
    icon: Minus,
    insertText: '---\n',
    group: 'Basic',
  },
  {
    id: 'toc',
    label: 'Table of contents',
    description: '插入 Word 目錄標記',
    icon: ListTree,
    insertText: '[TOC]\n',
    group: 'Basic',
  },
  {
    id: 'callout-note',
    label: 'Note',
    description: '插入筆記區塊',
    icon: StickyNote,
    insertText: '> [!NOTE]\n> 這裡輸入筆記內容',
    group: 'Callout',
  },
  {
    id: 'callout-tip',
    label: 'Tip',
    description: '插入提示區塊',
    icon: Info,
    insertText: '> [!TIP]\n> 這裡輸入提示內容',
    group: 'Callout',
  },
  {
    id: 'callout-warning',
    label: 'Warning',
    description: '插入警告區塊',
    icon: AlertTriangle,
    insertText: '> [!WARNING]\n> 這裡輸入警告內容',
    group: 'Callout',
  },
  {
    id: 'code-block',
    label: 'Code block',
    description: '插入有行號的程式碼區塊',
    icon: Code,
    insertText: '```typescript:ln\n// 程式碼貼在這裡\n```',
    cursorOffset: -4,
    group: 'Technical',
  },
  {
    id: 'mermaid',
    label: 'Mermaid chart',
    description: '插入 Mermaid 圖表',
    icon: FileCode,
    insertText: '```mermaid\ngraph TD;\n  A-->B;\n```',
    group: 'Technical',
  },
  {
    id: 'table',
    label: 'Table',
    description: '插入 Markdown 表格',
    icon: Table,
    insertText: '| 標題 1 | 標題 2 |\n| :--- | :--- |\n| 內容 1 | 內容 2 |',
    group: 'Technical',
  },
  {
    id: 'chat-left',
    label: 'User dialogue',
    description: '插入左側對話泡泡',
    icon: User,
    insertText: 'User ":: 這裡輸入對話內容',
    group: 'Chat',
  },
  {
    id: 'chat-right',
    label: 'AI dialogue',
    description: '插入右側對話泡泡',
    icon: Bot,
    insertText: 'AI ::" 這裡輸入對話內容',
    group: 'Chat',
  },
  {
    id: 'chat-center',
    label: 'System dialogue',
    description: '插入置中對話泡泡',
    icon: MessageCircle,
    insertText: 'System :": 這裡輸入系統訊息',
    group: 'Chat',
  },
  {
    id: 'image',
    label: 'Image',
    description: '插入圖片語法',
    icon: Image,
    insertText: '![圖片說明](url)',
    group: 'Media',
  },
  {
    id: 'frontmatter',
    label: 'Frontmatter',
    description: '插入書稿 metadata',
    icon: FileText,
    insertText: '---\ntitle: 書稿標題\nauthor: 作者\n---\n',
    group: 'Metadata',
  },
  {
    id: 'quick-mermaid',
    label: 'Quick mermaid',
    description: '插入流程圖範例',
    icon: BarChart,
    insertText: '```mermaid\ngraph TD;\n  開始-->撰寫\n  撰寫-->匯出\n```',
    group: 'Technical',
  },
];

export const QUICK_ACTION_IDS = [
  'h1',
  'h2',
  'h3',
  'frontmatter',
  'code-block',
  'mermaid',
  'callout-tip',
  'callout-note',
  'callout-warning',
  'chat-left',
  'chat-right',
  'table',
  'toc',
];

export const getQuickActions = () =>
  QUICK_ACTION_IDS
    .map((id) => EDITOR_COMMANDS.find((command) => command.id === id))
    .filter((command): command is CommandItem => Boolean(command));
